export const PRODUCTS = [
  {
    id: 1,
    productName: "oil cleanser",
    price: "15",
    description: "Melt the day away with this creamy cleanser",
    productImage: "/assets/curology-succulents-unsplash.jpg",
  },
  {
    id: 2,
    productName: "water cleanser",
    price: "15",
    description: "Cleanse your skin to prep for the day or night",
    productImage: "/assets/curology-water-cleanser-unsplash.jpg",
  },
  {
    id: 3,
    productName: "exfoliating serum",
    price: "20",
    description: "No flakes here",
    productImage: "/assets/pmv-chamara-exfoliating-unsplash.jpg",
  },
  {
    id: 4,
    productName: "vitamin c serum",
    price: "20",
    description: "Powerful antioxidant to brighten skin",
    productImage: "/assets/curology-vitamin-c-unsplash.jpg",
  },
  {
    id: 5,
    productName: "retinol serum",
    price: "25",
    description: "Anti-aging at its finest",
    productImage: "/assets/curology-retinol-unsplash.jpg",
  },
  {
    id: 6,
    productName: "sunscreen",
    price: "15",
    description: "Always make sure you have protection",
    productImage: "/assets/lina-sunscreen-unsplash.jpg",
  },
  {
    id: 7,
    productName: "gel moisturizer",
    price: "20",
    description: "Yes, oily skin needs moisture too",
    productImage: "/assets/curology-gel-unsplash.jpg",
  },
  {
    id: 8,
    productName: "cream moisturizer",
    price: "20",
    description: "A thicker, richer cream for dry skin",
    productImage: "/assets/pmv-chamara-cream-moisturizer-unsplash.jpg",
  },
  {
    id: 9,
    productName: "face oil",
    price: "25",
    description: "Glowy, moisturized skin",
    productImage: "/assets/birgith-roosipuu-facial-oil-unsplash.jpg",
  },
];
